version: '3'

services:
  prism:
    image: stoplight/prism:4
    container_name: prism-mock-server
    ports:
      - "3080:4010"
    command: mock -h 0.0.0.0 /app/openapi.yml --errors=false
    volumes:
      - ./openapi.yml:/app/openapi.yml
      - ./examples:/app/examples
    environment:
      - CORS=true